### ISSUE TITLE
How to support Pbr StandardMaterial

### ISSUE THREAD

**Issue by zzhgithub** [Multirious/bevy_tween#53]
I want to change color for 3d mesh with StandardMaterial.
StandardMaterial is a  asset. so I add a `Interpolator` Which Item is  StandardMaterial
and register the type

```rust
 #[cfg(all(feature = "bevy_pbr", feature = "bevy_asset",))]
        app.add_tween_systems(tween::asset_tween_system::<BaseColor>())
            .register_type::<tween::AssetTween<BaseColor>>();
```
 and  the demo  not went well. color not changed?

Code here:
https://github.com/zzhgithub/bevy_tween

```toml
[[example]]
name = "basic_color"
path = "examples/animation/basic_color.rs"
required-features = [
    "bevy_pbr",
    "bevy_asset",
]

```
